permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    permissions:
      contents: read     # checkout only
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: pr-preview-build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write        # REQUIRED
      pull-requests: write   # REQUIRED
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pr-preview-build
          path: build/

      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: build/
